// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIAG.Infrastructure.Configuracao;

#nullable disable

namespace SIAG.Infrastructure.Migrations
{
    [DbContext(typeof(SiagDbContext))]
    partial class SiagDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SIAG.Domain.Armazenagem.Cadastro.Models.AgrupadorAtivo", b =>
                {
                    b.Property<Guid>("AgrupadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AreaArmazenagemId")
                        .HasColumnType("int");

                    b.Property<int>("CdSequencia")
                        .HasColumnType("int");

                    b.Property<string>("Codigo1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DtAgrupador")
                        .HasColumnType("datetime2");

                    b.Property<int>("FgStatus")
                        .HasColumnType("int");

                    b.Property<int>("TpAgrupamento")
                        .HasColumnType("int");

                    b.HasKey("AgrupadorId");

                    b.ToTable("AgrupadorAtivo");
                });

            modelBuilder.Entity("SIAG.Domain.Armazenagem.Cadastro.Models.AreaArmazenagem", b =>
                {
                    b.Property<int>("AreaArmazenagemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaArmazenagemId"));

                    b.Property<Guid>("AgrupadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgrupadorReservadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CdIdentificacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<int>("FgStatus")
                        .HasColumnType("int");

                    b.Property<int>("NrLado")
                        .HasColumnType("int");

                    b.Property<int>("NrPosicaoX")
                        .HasColumnType("int");

                    b.Property<int>("NrPosicaoY")
                        .HasColumnType("int");

                    b.Property<int>("TipoAreaId")
                        .HasColumnType("int");

                    b.HasKey("AreaArmazenagemId");

                    b.HasIndex("AgrupadorId");

                    b.HasIndex("AgrupadorReservadoId");

                    b.HasIndex("EnderecoId");

                    b.HasIndex("TipoAreaId");

                    b.ToTable("AreaArmazenagem");
                });

            modelBuilder.Entity("SIAG.Domain.Armazenagem.Cadastro.Models.Caixa", b =>
                {
                    b.Property<string>("CaixaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("AgrupadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CdCor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CdGrudeTamanho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CdProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DtEmbalagem")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtEstufamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtExpedicao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtSorter")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FgRfid")
                        .HasColumnType("bit");

                    b.Property<int>("FgStatus")
                        .HasColumnType("int");

                    b.Property<int>("NrCaixa")
                        .HasColumnType("int");

                    b.Property<int>("NrPares")
                        .HasColumnType("int");

                    b.Property<int>("PalletId")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("ProgramaId")
                        .HasColumnType("int");

                    b.Property<decimal>("QtPeso")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CaixaId");

                    b.HasIndex("AgrupadorId");

                    b.ToTable("Caixa");
                });

            modelBuilder.Entity("SIAG.Domain.Armazenagem.Cadastro.Models.Deposito", b =>
                {
                    b.Property<int>("DepositoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepositoId"));

                    b.Property<string>("NmDeposito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepositoId");

                    b.ToTable("Deposito");
                });

            modelBuilder.Entity("SIAG.Domain.Armazenagem.Cadastro.Models.Endereco", b =>
                {
                    b.Property<int>("EnderecoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnderecoId"));

                    b.Property<int>("FgStatus")
                        .HasColumnType("int");

                    b.Property<string>("NmEndereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QtEstoqueMaximo")
                        .HasColumnType("int");

                    b.Property<int>("QtEstoqueMinimo")
                        .HasColumnType("int");

                    b.Property<int>("RegiaoTrabalhoId")
                        .HasColumnType("int");

                    b.Property<int>("SetorTrabalhoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoEnderecoId")
                        .HasColumnType("int");

                    b.Property<int>("TpPreenchimento")
                        .HasColumnType("int");

                    b.HasKey("EnderecoId");

                    b.HasIndex("RegiaoTrabalhoId");

                    b.HasIndex("SetorTrabalhoId");

                    b.HasIndex("TipoEnderecoId");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("SIAG.Domain.Armazenagem.Cadastro.Models.Equipamento", b =>
                {
                    b.Property<int>("EquipamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipamentoId"));

                    b.Property<string>("CdLeituraPendente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CdUltimaLeitura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DtInclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtManutencao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtUltimaLeitura")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<int>("EquipamentoModeloId")
                        .HasColumnType("int");

                    b.Property<int>("FgStatus")
                        .HasColumnType("int");

                    b.Property<int>("FgStatusTrocaCaracol")
                        .HasColumnType("int");

                    b.Property<string>("NmAbreviadoEquipamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NmEquipamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NmIdentificador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NmIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NmObservacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NmUsuarioLiberacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OperadorId")
                        .HasColumnType("int");

                    b.Property<int>("SetorTrabalhoId")
                        .HasColumnType("int");

                    b.HasKey("EquipamentoId");

                    b.ToTable("Equipamento");
                });

            modelBuilder.Entity("SIAG.Domain.Armazenagem.Cadastro.Models.Pallet", b =>
                {
                    b.Property<int>("PalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PalletId"));

                    b.Property<Guid>("AgrupadorAtivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AreaArmazenagemId")
                        .HasColumnType("int");

                    b.Property<string>("CdIdentificacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DtUltimaMovimentacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("FgStatus")
                        .HasColumnType("int");

                    b.Property<int>("QtUtilizacao")
                        .HasColumnType("int");

                    b.HasKey("PalletId");

                    b.HasIndex("AgrupadorAtivoId");

                    b.HasIndex("AreaArmazenagemId");

                    b.ToTable("Pallet");
                });

            modelBuilder.Entity("SIAG.Domain.Armazenagem.Cadastro.Models.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PedidoId"));

                    b.Property<int>("CdBox")
                        .HasColumnType("int");

                    b.Property<int>("CdCanal")
                        .HasColumnType("int");

                    b.Property<int>("CdCliente")
                        .HasColumnType("int");

                    b.Property<string>("CdEstabelecimento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CdLote")
                        .HasColumnType("int");

                    b.Property<int>("CdOrdemExportacao")
                        .HasColumnType("int");

                    b.Property<int>("CdOrdemExportacaoDefinitiva")
                        .HasColumnType("int");

                    b.Property<int>("CdPedido")
                        .HasColumnType("int");

                    b.Property<string>("CdRota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CdSequenciaExpedicao")
                        .HasColumnType("int");

                    b.Property<int>("CdVeiculoExportacao")
                        .HasColumnType("int");

                    b.Property<int>("CdVeiculoExportacaoDefinitiva")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtImplantacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtImportacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtPredata")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtPrevisaoExportacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("FgSku")
                        .HasColumnType("int");

                    b.Property<int>("FgStatus")
                        .HasColumnType("int");

                    b.Property<int>("NotaFiscalId")
                        .HasColumnType("int");

                    b.Property<int>("QtAcessorio")
                        .HasColumnType("int");

                    b.Property<int>("QtCaixa")
                        .HasColumnType("int");

                    b.Property<decimal>("QtCubagemAcessorio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QtCubagemCaixa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QtCubagemDisplay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QtCubagemExpositores")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QtDisplay")
                        .HasColumnType("int");

                    b.Property<int>("QtExpositores")
                        .HasColumnType("int");

                    b.Property<string>("TpCarga")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TpCargaAglutinado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransportadoraId")
                        .HasColumnType("int");

                    b.HasKey("PedidoId");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("SIAG.Domain.Armazenagem.Cadastro.Models.Programa", b =>
                {
                    b.Property<int>("ProgramaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramaId"));

                    b.Property<string>("CdDeposito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CdDocumento")
                        .HasColumnType("int");

                    b.Property<string>("CdEquipamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CdEstabelecimento")
                        .HasColumnType("int");

                    b.Property<int>("CdFabrica")
                        .HasColumnType("int");

                    b.Property<int>("CdPrograma")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtLiberacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("FgTipo")
                        .HasColumnType("int");

                    b.Property<decimal>("QtAlturaCaixa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QtComprimentoCaixa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QtLarguraCaixa")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProgramaId");

                    b.ToTable("Programa");
                });

            modelBuilder.Entity("SIAG.Domain.Armazenagem.Cadastro.Models.RegiaoTrabalho", b =>
                {
                    b.Property<int>("RegiaoTrabalhoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegiaoTrabalhoId"));

                    b.Property<int>("DepositoId")
                        .HasColumnType("int");

                    b.Property<string>("NmRegiaoTrabalho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegiaoTrabalhoId");

                    b.HasIndex("DepositoId");

                    b.ToTable("RegiaoTrabalho");
                });

            modelBuilder.Entity("SIAG.Domain.Armazenagem.Cadastro.Models.SetorTrabalho", b =>
                {
                    b.Property<int>("SetorTrabalhoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SetorTrabalhoId"));

                    b.Property<int>("DepositoId")
                        .HasColumnType("int");

                    b.Property<string>("NmSetorTrabalho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SetorTrabalhoId");

                    b.HasIndex("DepositoId");

                    b.ToTable("SetorTrabalho");
                });

            modelBuilder.Entity("SIAG.Domain.Armazenagem.Cadastro.Models.TipoArea", b =>
                {
                    b.Property<int>("TipoAreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoAreaId"));

                    b.Property<string>("NmTipoArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoAreaId");

                    b.ToTable("TipoArea");
                });

            modelBuilder.Entity("SIAG.Domain.Armazenagem.Cadastro.Models.TipoEndereco", b =>
                {
                    b.Property<int>("TipoEnderecoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoEnderecoId"));

                    b.Property<string>("NmTipoEndereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoEnderecoId");

                    b.ToTable("TipoEndereco");
                });

            modelBuilder.Entity("SIAG.Domain.Armazenagem.Cadastro.Models.Turno", b =>
                {
                    b.Property<int>("TurnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurnoId"));

                    b.Property<int>("CdTurno")
                        .HasColumnType("int");

                    b.Property<bool>("DiaAnterior")
                        .HasColumnType("bit");

                    b.Property<bool>("DiaSucessor")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DtFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtInicio")
                        .HasColumnType("datetime2");

                    b.HasKey("TurnoId");

                    b.ToTable("Turno");
                });

            modelBuilder.Entity("SIAG.Domain.Armazenagem.Cadastro.Models.AreaArmazenagem", b =>
                {
                    b.HasOne("SIAG.Domain.Armazenagem.Cadastro.Models.AgrupadorAtivo", "Agrupador")
                        .WithMany()
                        .HasForeignKey("AgrupadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIAG.Domain.Armazenagem.Cadastro.Models.AgrupadorAtivo", "AgrupadorReservado")
                        .WithMany()
                        .HasForeignKey("AgrupadorReservadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIAG.Domain.Armazenagem.Cadastro.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIAG.Domain.Armazenagem.Cadastro.Models.TipoArea", "TipoArea")
                        .WithMany()
                        .HasForeignKey("TipoAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agrupador");

                    b.Navigation("AgrupadorReservado");

                    b.Navigation("Endereco");

                    b.Navigation("TipoArea");
                });

            modelBuilder.Entity("SIAG.Domain.Armazenagem.Cadastro.Models.Caixa", b =>
                {
                    b.HasOne("SIAG.Domain.Armazenagem.Cadastro.Models.AgrupadorAtivo", "Agrupador")
                        .WithMany()
                        .HasForeignKey("AgrupadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agrupador");
                });

            modelBuilder.Entity("SIAG.Domain.Armazenagem.Cadastro.Models.Endereco", b =>
                {
                    b.HasOne("SIAG.Domain.Armazenagem.Cadastro.Models.RegiaoTrabalho", "RegiaoTrabalho")
                        .WithMany()
                        .HasForeignKey("RegiaoTrabalhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIAG.Domain.Armazenagem.Cadastro.Models.SetorTrabalho", "SetorTrabalho")
                        .WithMany()
                        .HasForeignKey("SetorTrabalhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIAG.Domain.Armazenagem.Cadastro.Models.TipoEndereco", "TipoEndereco")
                        .WithMany()
                        .HasForeignKey("TipoEnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegiaoTrabalho");

                    b.Navigation("SetorTrabalho");

                    b.Navigation("TipoEndereco");
                });

            modelBuilder.Entity("SIAG.Domain.Armazenagem.Cadastro.Models.Pallet", b =>
                {
                    b.HasOne("SIAG.Domain.Armazenagem.Cadastro.Models.AgrupadorAtivo", "AgrupadorAtivo")
                        .WithMany()
                        .HasForeignKey("AgrupadorAtivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIAG.Domain.Armazenagem.Cadastro.Models.AreaArmazenagem", "AreaArmazenagem")
                        .WithMany()
                        .HasForeignKey("AreaArmazenagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgrupadorAtivo");

                    b.Navigation("AreaArmazenagem");
                });

            modelBuilder.Entity("SIAG.Domain.Armazenagem.Cadastro.Models.RegiaoTrabalho", b =>
                {
                    b.HasOne("SIAG.Domain.Armazenagem.Cadastro.Models.Deposito", "Deposito")
                        .WithMany()
                        .HasForeignKey("DepositoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deposito");
                });

            modelBuilder.Entity("SIAG.Domain.Armazenagem.Cadastro.Models.SetorTrabalho", b =>
                {
                    b.HasOne("SIAG.Domain.Armazenagem.Cadastro.Models.Deposito", "Deposito")
                        .WithMany()
                        .HasForeignKey("DepositoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deposito");
                });
#pragma warning restore 612, 618
        }
    }
}
